export const AUTH_INPORGRESS = "AUTH_INPORGRESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const ADD_STUDENT_INPROGRESS = "ADD_STUDENT_INPROGRESS";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";
export const SET_SESSION = "SET_SESSION";
export const END_SESSION = "END_SESSION";
export const SET_STATUS = "SET_STATUS";

export const SET_NAME = "SET_NAME";
export const SELECT_NAME = "SELECT_NAME";
export const FETCH_STUDENT_INPROGRESS = "FETCH_STUDENT_INPROGRESS";
export const FETCH_STUDENT_SUCCESS = "FETCH_STUDENT_SUCCESS";
export const FETCH_STUDENT_ERROR = "FETCH_STUDENT_ERROR";

export const WRITE_RESPONSE_INPROGRESS = "WRITE_RESPONSE_INPROGRESS";
export const WRITE_RESPONSE_SUCCESS = "WRITE_RESPONSE_SUCCESS";
export const WRITE_RESPONSE_ERROR = "WRITE_RESPONSE_ERROR";

export const LISTEN_TO_RESPONSE = "LISTEN_TO_RESPONSE";
export const LISTEN_TO_RESPONSE_ERROR = "LISTEN_TO_RESPONSE_ERROR";
