export const AUTH_INPORGRESS = "AUTH_INPORGRESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const ADD_STUDENT_INPROGRESS = "ADD_STUDENT_INPROGRESS";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";
export const END_SESSION = "END_SESSION";
export const SET_STATUS = "SET_STATUS";
